added the branch, first push I didn't check out the branch before i pushed it.
learn-academy-2022-alpha/week-6-assessment-omarbowen01 pull request #1
Opened 2022-04-05 16:21 UTC by omarbowen01

…rting work

2022-04-06 23:03 UTC, WalkerTexas-coder requested changes
This PR has no code to review... Please update this PR with the code to review Iand I will get around to it.

2022-04-07 17:07 UTC, omarbowen01 commented
PR has been updated with code. Please let me know if you need anything else. Thank You!

2022-04-07 19:59 UTC, WalkerTexas-coder approved these changes
Okay Omar this sis good stuff. Thank you for figuring out some of the git issues but I do want to see that you know how to research and get these issues squared away. Good work on the assessment. Double check your user stories and perhaps practice writing some out before you head into interviews so you can ask questions about what the context of the internship workflow will be like. Approved!

2022-04-07 19:59 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +}
nice!

2022-04-07 19:59 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +}
Very clean!

2022-04-07 19:59 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +  arr.filter(v=> sum += v ** 3)
You used filter effectively here. Recommend looking into .reduce().

2022-04-07 19:59 UTC, WalkerTexas-coder commented on rails-commenting.rb
> +    #@post is an instance variable called on the Database and using the create method to make a new instance in the database using the private method blog_post_params.
Well done!

2022-04-07 19:59 UTC, WalkerTexas-coder commented on interview-questions.md
>  5. As a developer, you are making an application to manage your to do list. Create 10 user stories that will help you get your application started. Read more about [user stories](https://www.atlassia
This is almost correct. What we want to describe is what the user will experience on our platform so we can build out the features that will match that experience. 

"As a user I can see a plus button that will navigate me to a page where I can create a to-do item"

2022-04-07 20:41 UTC, merged